# Generated by Django 5.0 on 2023-12-17 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesetter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='overlap_day_before',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(0)]),
        ),
    ]
