# Generated by Django 5.0 on 2023-12-17 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesetter', '0002_alter_customer_overlap_day_before'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='wsp',
        ),
        migrations.AddField(
            model_name='sku',
            name='wsp',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='overlap_day_after',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(0)]),
        ),
    ]
