# Generated by Django 5.0 on 2023-12-20 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesetter', '0003_remove_pricing_wsp_sku_wsp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Period',
            new_name='Promotion',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='wsp',
        ),
        migrations.AddField(
            model_name='pricing',
            name='wsp',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricesetter.customer')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricesetter.sku')),
            ],
        ),
    ]
